algo = input('Escreva algo ')
print(f'O tipo primitivo desse valor é {type(algo)}')
print(f'Só tem espacos? {algo.isspace()}')
print('{} é um numero? {}'.format(algo, algo.isnumeric()))
print('{} é uma letra? {}'.format(algo, algo.isalpha()))
print('{} é alfanumérico? {}'.format(algo, algo.isalnum()))
print(f'{algo} está em letras maiùsculas? {algo.isupper()}')
print(f'{algo} está em minusculo? {algo.islower()}')
print(f'{algo} está captalizado? {algo.istitle()}')
