nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print(f'Seu nome em maiusculo é: {nome.upper()}')
print(f'Seu nome em minúsculo é: {nome.lower()}')
letras = len(nome) - nome.count(' ')
print(f'Seu nome tem ao todo {letras} letras')
divisao = nome.split()
print(f"Seu primeiro nome '{divisao[0]}' tem {len(divisao[0])} letras")